version: "2" # required to adjust maintainability checks
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_patterns:
    - 'spec/**/*'
    - 'vendor/**/*'
  eslint:
    enabled: true
    exclude_patterns:
    - 'vendor/**/*'
  fixme:
    enabled: true
    exclude_patterns:
    - 'vendor/**/*'
  reek:
    enabled: true
  rubocop:
    enabled: true

exclude_patterns:
  - 'node_modules/'
  - 'public/'
  - 'spec/'
  - 'tmp/'
  - 'vendor/'
